### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant

### ISSUE THREAD

**Issue by jakal23** [data2viz/Charts.kt-samples#1]
```
at kotlinx.datetime.Instant.(Instant.kt:78)
at kotlinx.datetime.Clock$System.now(Clock.kt:17)
at io.data2viz.charts.logging.LoggingKt.(Logging.kt:21)
at io.data2viz.charts.logging.LoggingKt.access$timeInfo(Logging.kt:1)
at io.data2viz.charts.logging.KLogger.verbose$core_release(Logging.kt:45)
at io.data2viz.charts.chart.internal.ChartImpl.(ChartImpl.kt:563)
at io.data2viz.charts.chart.ChartKt.chart(Chart.kt:39)
at com.atcc.drivingtests.app.view.RankChart.applyChart(RankChart.kt:39)
at com.atcc.drivingtests.app.view.RankChart.(RankChart.kt:28)
at com.atcc.drivingtests.ui.rank.RankFragment.onCreateView(RankFragment.kt:24)

   Caused by java.lang.ClassNotFoundException: Didn't find class "java.time.Instant" on path: DexPathList[[zip file "/data/app/com.atcc.drivingtests-1/base.apk", zip file "/data/app/com.atcc.drivingtests-1/split_config.armeabi_v7a.apk", zip file "/data/app/com.atcc.drivingtests-1/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.atcc.drivingtests-1/lib/arm, /data/app/com.atcc.drivingtests-1/base.apk!/lib/armeabi-v7a, /data/app/com.atcc.drivingtests-1/split_config.armeabi_v7a.apk!/lib/armeabi-v7a, /data/app/com.atcc.drivingtests-1/split_config.xxhdpi.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
```

If you open the sdk documentation https://developer.android.com/reference/java/time/Instant.html you see in the upper right corner "added in API level 26" which means the class is not available on older android devices.

Build gradle file
```
implementation 'io.data2viz.charts:core:1.0.12'
implementation("io.data2viz.d2v:d2v-viz:0.10.6")
```

[Linked issue
](https://github.com/data2viz/data2viz/issues/258)

**Comment by LouisCAD** [comment]
Hello, next version of Charts.kt will have [core library desugaring](https://developer.android.com/studio/write/java8-support) enabled, which should fix the issue.
